### ISSUE TITLE
Back Button for New Search

### ISSUE THREAD

**Issue by uakirmak** [Hoksolinvan/SENG480A#13]
**Feature name:** Back Button for New Search

**Description:** Add a "Back" button that allows users to return to the quiz to perform a new search after completing a quiz or receiving search results, without having to navigate all the way back to the start.

**Pain reliever:** This feature will improve user navigation by allowing users to quickly retry or modify their search, making the experience smoother and more intuitive.

**Requires:**

-     Frontend implementation of a "Back" button
-     Ensure quiz state resets when users choose to search again

**Due:** Milestone 2

**Status:** Not started

**Time estimation:** 1 day

**Comment by harrylam-quay** [comment]
![Screenshot 2024-10-10 at 23-12-11 ](https://github.com/user-attachments/assets/2c811720-0ca3-40d5-83c9-335f7eab9437)
I added a simple button to reload the page and return to the quiz. I might think of more seamless ways to do this, instead of reloading the webpage.

**Comment by harrylam-quay** [comment]
No longer applicable post-pivot. Close?
