### ISSUE TITLE
CSS and website layout

### ISSUE THREAD

**Issue by uakirmak** [Hoksolinvan/SENG480A#2]
We need to improve the overall color scheme and patterns of our app.

**Comment by harrylam-quay** [comment]
Will work on it. I will assume we are keeping the same color scheme as the mock UI?

**Comment by harrylam-quay** [comment]
I'm thinking of moving About, Contact to the Footer. The header will then only have the logo, log in, and sign up. What do you think?

**Comment by uakirmak** [comment]
Hi Harry,

I think those links could be important. I would not prefer to move them to
footer. If you do not like them to appear, maybe we can implement a
dropdown menu of some sort, what do you think?

Umit

**Comment by harrylam-quay** [comment]
Hi Umit. Makes sense. I'll keep them there then. I already added a drop-down menu (though it looks a bit ugly, which is why I thought of making them go in the footer instead). I'll try beautify drop-down menu

**Comment by uakirmak** [comment]
**Feature name:** Website Design and CSS Styling

**Description:** Create a visually appealing and user-friendly design for the website, ensuring that the layout is clean, responsive, and easy to navigate. Focus on modern, minimalistic design with intuitive user interaction.

**Pain reliever:** Young users prefer clean, visually appealing designs and tend to lose interest in cluttered or difficult-to-navigate websites. A modern design will enhance user engagement and improve the overall experience.

**Requires:**

-     Finalizing the layout and structure of the website
-     Implementing responsive CSS to ensure the website works across devices
-     Refining the design elements to align with the target audience

**Due**: 

-     Milestone 1: Basic design and layout is created.
-     Milestone 2: Through user feedback, a revision will be considered

**Status:** The basic layout is completed; further refinement is needed to improve responsiveness and styling. CSS animations and adjustments to the UI are in progress.

Time estimation: 4 days
