### ISSUE TITLE
Further Development of Quiz Questions

### ISSUE THREAD

**Issue by uakirmak** [Hoksolinvan/SENG480A#3]
We need to develop and refine the quiz questions for our app.

**Comment by Hoksolinvan** [comment]
I think insights gathered from high school students provided by Karn and Sam would be useful

**Comment by uakirmak** [comment]
We changed from the original idea of a personality quiz to a more planning/preferences type of questions in the quiz. 
The basic idea is implemented in the MVP with two multiple-choice questions: 1) choice of academic program 2) preference for academic reputation.

**Comment by uakirmak** [comment]
We implemented two basic questions. Now we need to discuss refining these questions further and build an entryway to a more complex search functionality

**Comment by uakirmak** [comment]
**Feature name:** Further Development of Assessment Questions

**Description:** We pivoted from the original personality quiz to a simplified quiz that gathers user preferences through a few planning-related questions. The MVP includes two multiple-choice questions: 1) choice of academic program and 2) preference for academic reputation. Instead of overwhelming users with a complex UI, we will ask a few targeted questions to provide the most relevant results. Users can later opt to perform a more detailed search if they wish.

**Pain reliever:** Students are often overwhelmed by complex and lengthy forms. By simplifying the initial quiz, we can quickly gather preferences and provide relevant results, making the experience more user-friendly and reducing the decision fatigue associated with detailed searches.

**Requires:**

-     Refining the current MVP questions and logic to ensure the accuracy and relevance of results
-     Backend integration to connect user responses to relevant program data
-     Option to perform a more detailed search after the initial results are displayed

**Due:** 

-     Milestone 2

**Status:** MVP with two basic questions implemented—further refinement of quiz logic and connection to program results needed.

**Time estimation:** 3 days

**Comment by harrylam-quay** [comment]
No longer applicable post-pivot. Close?
