### ISSUE TITLE
Backend Integration with Algorithm

### ISSUE THREAD

**Issue by uakirmak** [Hoksolinvan/SENG480A#4]
We need to enhance the backend to access education-related data and integrate it with our algorithm.

---------

- Feature name: Algorithm
- Description: Algorithm to produce appropriate results based on assessment answers provided by user
- Pain reliever: young students typically do not have much time and knowledge to navigate the plethora of information scattered online. Furthermore, it is difficult to keep track of various deadlines and requirements for each institutions the student applies or plans to apply to.
- Requires: research necessary elements the student might need to know, develop the algorithm
- Due: Milestone 2
- Status: working on elements, to work on the algorithm
 - Time estimation: 2 days(?)

**Comment by Hoksolinvan** [comment]
Working on it!

**Comment by uakirmak** [comment]
We pivoted from the original idea (having a personality quiz that would provide a match of the academic program to the user). Currently, there is **no need** for a sophisticated algorithm. However, we can still implement a version of the algorithm that would short-list the relevant (or matching) programs for the user and provide a short-list of options, thus alleviating the pain of going through a sophisticated search engine. **We still need to discuss as a group** how we want to move forward with this idea.

**Comment by uakirmak** [comment]
**Feature name:** Algorithm

**Description:** Develop an algorithm to generate appropriate results based on the assessment answers provided by the user, offering a short-list of relevant academic programs.

**Pain reliever:** Young students often lack the time and expertise to sift through the abundance of information available online. Additionally, keeping track of deadlines and requirements for various institutions can be overwhelming. This algorithm will ease these challenges by presenting relevant program options, streamlining the application process for students.

**Requires:**

-     Researching the essential elements students need to know
-     Developing an algorithm to match student preferences with relevant academic programs
-     Potential refinement to offer a more simplified version of the algorithm

**Due:**
    

-      Milestone 1 (**completed**): Provide initial results based on a few preferences; lacks sophistication
-      Milestone 2 (**needs to be done**): Initial version of the algorithm, providing a short-list of relevant programs based on assessment results


Status: We have pivoted from the original idea (a personality quiz to match academic programs). Currently, a sophisticated algorithm is not necessary. However, a simpler version could still be implemented to short-list matching programs, easing the student's burden of navigating search engines. We need to finalize the approach as a team and decide on how we want to move forward with this version.

Time estimation: 4 days (tentative, depending on team discussions)

**Comment by harrylam-quay** [comment]
No longer applicable post-pivot. Close?
