### ISSUE TITLE
User Results Display and Presentation

### ISSUE THREAD

**Issue by uakirmak** [Hoksolinvan/SENG480A#5]
**Feature name:** Result Presentation to User

**Description:** Create an informative and visually appealing presentation of assessment results to users. The presentation should be minimally textual and visually stimulating to capture young users' short attention span, ensuring results are easy to understand and engaging.

**Pain reliever:** Young students typically have shorter attention spans and a general aversion to reading long text. They also lack the time and knowledge to navigate the vast amount of scattered information online. Providing a visually appealing format with minimal text while still being informative, and consolidating this information in one place, will ease these difficulties.

**Requires:**

-     Enhancing the visual design for better user engagement
-     Connecting to the results obtained from the backend
-     Adding animations or visual elements to enrich the user experience
-     Future integration with the profile page to allow saving application deadlines

**Due:**

-     Milestone 1: Basic visual designs for mock-quiz results (Completed)
-     For Milestone 2: Connect results to the actual algorithm from the backend and improve visual presentation 

**Status:** Basic visual designs are complete. Currently, results are presented in textual format, showing application dates clearly. The next steps are to add visual animations and other design elements, and connect the results to the backend. Additionally, a functionality that records application deadlines to the user's profile will be integrated once the profile page is built.

**Time estimation:** 36 hours 

Earlier notes (pre Oct 10): 
----------

Original comment: We need to improve how the results will be displayed and presented to users.

----------

- Feature name: Result presentation to user
- Description: Informative and visually appealing presentation of assessment results to user. Should be minimally textual and visually stimulating to capture young users' short attention span.
- Pain reliever: young students typically has a shorter attention span and a general aversion to reading long text. They also do not have much time and knowledge to navigate the plethora of information scattered online. Having a visually appealing with minimal text while still being informative, with informative congregated into one place will ease these pains.
- Requires: visual designs, connecting to assessment results obtained from the back-end.
- Due:
     + Milestone 1: visual designs for the mock-quiz
     + Milestone 2: connect actual algorithm from back-end
- Status: basic visual designs done, need to add more elements to make it more visual appealing, connect to back-end for Milestone 2
- Time estimation: 12 hours

**Comment by Hoksolinvan** [comment]
Will work on it!

**Comment by uakirmak** [comment]
Currently, the app provides results in textual format and clearly shows the application dates. We haven't added fancy visual animations. This could be the next step. Further, we need to add a functionality that records this application deadline to user's profile (once we build the profile page functionality)

**Comment by Hoksolinvan** [comment]
The backend integration has already been set up where the quiz results are saved to a database relation. When moving on to creating profile pages and user information we would be able to create relations for each specific users and establish one-to-many. 

Currently working on date submissions and will push the additional feature after design elements are properly integrated.

**Comment by harrylam-quay** [comment]
Decrepit post-pivot
